name: Run tests

on:

  workflow_dispatch:
  
  schedule:
    - cron: '0 9 * * *'
  
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Install Jest
        run: npm install jest

      - name: Run tests
        run: npx playwright test
